spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:inditexdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      auto-commit: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: embedded
      # data-locations: classpath:db/migrations/data.sql
      schema-locations: classpath:db/migrations/schema.sql
      platform: h2

  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
    settings:
      web-allow-others: true
      trace: true

server:
  #  port: 8000
  compression:
    enabled: true
    mime-types: application/json

# swagger http://localhost:8000/swagger-ui/index.html#/