DROP TABLE IF EXISTS GET_OFFERS_INTERVALS;

DROP TABLE IF EXISTS OFFER;

CREATE TABLE OFFER
(
    OFFER_ID    INT                      NOT NULL,
    BRAND_ID    VARCHAR                  NOT NULL,
    START_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE    TIMESTAMP WITH TIME ZONE NOT NULL,
    PRICE_LIST  INT                      NOT NULL,
    PARTNUMBER  VARCHAR                  NOT NULL,
    PRIORITY    INT                      NOT NULL,
    PRICE       DOUBLE PRECISION         NOT NULL,
    CURR        VARCHAR                  NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone
);

ALTER TABLE OFFER
    ADD CONSTRAINT PK_OFFER UNIQUE (OFFER_ID);

CREATE INDEX IF NOT EXISTS IDX_OFFER_ID ON OFFER (OFFER_ID);
CREATE INDEX IF NOT EXISTS IDX_OFFER_BRAND_ID ON OFFER (BRAND_ID);
CREATE INDEX IF NOT EXISTS IDX_OFFER_START_DATE ON OFFER (START_DATE);
CREATE INDEX IF NOT EXISTS IDX_OFFER_END_DATE ON OFFER (END_DATE);

CREATE VIEW GET_OFFERS_INTERVALS AS
SELECT OF7.OFFER_ID OFFER_ID, OF7.BRAND_ID BRAND_ID, OF8.START_DATE START_DATE, OF8.END_DATE END_DATE,
       OF7.PRICE_LIST PRICE_LIST, OF7.PRIORITY PRIORITY, OF7.PRICE PRICE, OF7.PARTNUMBER PARTNUMBER, OF7.CURR CURR,
       OF7.MODIFIED_AT MODIFIED_AT, OF7.CREATED_AT CREATED_AT
FROM (
         SELECT OF6.*, MAX(OF5.PRIORITY) PRIORITY, MAX(OF5.OFFER_ID) OFFER_ID FROM
             (
                 SELECT OF3.START_DATE, DATEADD(SECOND , -1, MIN(OF4.START_DATE)) AS END_DATE
                 FROM
                     (SELECT OF1.START_DATE FROM OFFER OF1
                      UNION
                      SELECT OF2.END_DATE FROM OFFER OF2) OF3
                         INNER JOIN
                     (SELECT OF1.START_DATE FROM OFFER OF1
                      UNION
                      SELECT OF2.END_DATE FROM OFFER OF2) OF4
                     ON OF3.START_DATE < OF4.START_DATE
                 GROUP BY OF3.START_DATE
             ) OF6
                 INNER JOIN OFFER OF5
                            ON OF5.START_DATE <= OF6.START_DATE AND OF5.END_DATE>= OF6.END_DATE GROUP BY OF6.START_DATE
     ) OF8
         INNER JOIN OFFER OF7 ON OF7.OFFER_ID = OF8.OFFER_ID;
