DROP TABLE IF EXISTS OFFER;

CREATE TABLE OFFER
(
    OFFER_ID    INT                      NOT NULL,
    BRAND_ID    VARCHAR                  NOT NULL,
    START_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE    TIMESTAMP WITH TIME ZONE NOT NULL,
    PRICE_LIST  INT                      NOT NULL,
    PARTNUMBER  VARCHAR                  NOT NULL,
    PRIORITY    INT                      NOT NULL,
    PRICE       DOUBLE PRECISION         NOT NULL,
    CURR        VARCHAR                  NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now()):: timestamp(0) without time zone
);

ALTER TABLE OFFER
    ADD CONSTRAINT PK_OFFER UNIQUE (OFFER_ID);

CREATE INDEX IF NOT EXISTS IDX_OFFER_ID ON OFFER (OFFER_ID);
CREATE INDEX IF NOT EXISTS IDX_OFFER_BRAND_ID ON OFFER (BRAND_ID);
CREATE INDEX IF NOT EXISTS IDX_OFFER_START_DATE ON OFFER (START_DATE);
CREATE INDEX IF NOT EXISTS IDX_OFFER_END_DATE ON OFFER (END_DATE);
